version: '3.5'

services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: financesdb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - finances
    restart: unless-stopped

networks:
  finances:
    driver: bridge

volumes:
  postgres: