version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: financesdb
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - finances
    restart: unless-stopped

  localstack:
    container_name: localstack
    hostname: localstack
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fakeaccess
      - AWS_SECRET_KEY_ID=fakesecret
      - SERVICES=secretmanager, ssm, sqs, s3
      - LAMBDA_EXECUTOR=docker
      - DATA_DIR=/tmp/localstack/data
      - DOCKER-HOST=unix:///var/run/docker.sock
      - DEBUG=1
    ports:
      - "4566:4566"
    networks:
      - finances
    volumes:
      - "./init-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - localstack-data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - finances
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
        - "3000:3000"
    networks:
      - finances
    restart: unless-stopped

networks:
  finances:
    driver: bridge

volumes:
  postgres-data:
  localstack-data:
  prometheus-data:
  grafana-data: