spring:
  h2:
    console:
      enabled: true
      path: /finances-db-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:}
    url: ${DB_URL:jdbc:h2:mem:finances-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true